# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster
  region: ap-norheast-1

nodeGroups:
  - name: ng-1
    instanceType: t3a.nano
    desiredCapacity: 1
  - name: ng-2
    instanceType: t3a.nano
    desiredCapacity: 1
  - name: ng-3
    instanceType: t3a.nano
    desiredCapacity: 1