apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-deployment
  labels:
    app: go-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: go-server-container
        image: iaizawa0623/go_http_server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 64Mi
            cpu: "0.2"
        ports:
        - containerPort: 80
